server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/frontend-gestion/browser;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /usuarios/ { proxy_pass http://localhost:3000; }
    location /clientes/ { proxy_pass http://localhost:3000; }
    location /dashboard/ { proxy_pass http://localhost:3000; }
    location /proyectos/ { proxy_pass http://localhost:3000; }
    location /tareas/ { proxy_pass http://localhost:3000; }
}